### ISSUE TITLE
postprocess_VEP_json.py error

### ISSUE THREAD

**Issue by Fazulur** [phenopolis/phenopolis#168]
Dear Team,

We installed phenopolis to our HPC and tried to use run_VEP.sh and postprocess_VEP_json.py scripts prior to import json to mongodb.

run_VEP.sh script is pointing to server. Could you please help me is there any possibilities to modify the script so that i can redirect all inputs from HPC? 

I ran VEP with custom plugins and added Exac, ESP, exaac, 1000G annotations. I tried to run postprocess_VEP_json.py on vep json and it was giving the below error. 

Command I used:

postprocess_VEP_json.py --file vep-json/results/48samples.vep.json --exac ref_data/Hsapiens/hs37d5/variation/exac.vcf.gz

ERROR:

{id:.,most_severe_consequence:upstream_gene_variant,input:1\t10138\t.\tTAACCC\tT\t71.66\tPASS\tAC=1;AF=0.009434;AN=94;BaseQRankSum=-0.366;DP=4555;ExcessHet=41.744;FS=0;InbreedingCoeff=-0.3418;MLEAC=7;MLEAF=0.066;MQ=13.94;MQRankSum=1.98;NEGATIVE_TRAIN_SITE;QD=10.24;ReadPosRankSum=0.431;SOR=0.148;VQSLOD=-2.554;culprit=DP\tGT:AD:DP:GQ:PL\t0/0:122,0:122:0:0,0,2394\t0/0:71,0:71:0:0,0,754\t0/1:5,2:7:53:53,0,114\t0/0:89,0:89:0:0,0,1164\t0/0:108,0:108:0:0,0,1394\t0/0:95,0:95:0:0,0,1455\t0/0:86,0:86:0:0,0,889\t0/0:91,0:91:0:0,0,1003\t0/0:88,0:88:0:0,0,1351\t0/0:127,0:127:0:0,0,1759\t0/0:90,0:90:0:0,0,1179\t0/0:94,0:94:0:0,0,1033\t0/0:99,0:99:0:0,0,1404\t0/0:111,0:111:0:0,0,1343\t0/0:118,0:118:0:0,0,1163\t0/0:95,0:95:0:0,0,1402\t0/0:89,0:89:0:0,0,1012\t0/0:56,0:56:0:0,0,813\t0/0:55,0:55:0:0,0,685\t0/0:68,0:68:0:0,0,440\t0/0:67,0:67:0:0,0,1044\t0/0:44,0:44:0:0,0,554\t0/0:73,0:73:0:0,0,803\t0/0:70,0:70:0:0,0,1077\t0/0:89,0:89:0:0,0,949\t0/0:126,0:126:0:0,0,1990\t0/0:69,0:69:0:0,0,755\t./.:62,0:62:.:0,0,0\t0/0:59,0:59:0:0,0,1023\t0/0:67,0:67:0:0,0,879\t0/0:53,0:53:0:0,0,573\t0/0:106,0:106:0:0,0,1295\t0/0:95,0:95:0:0,0,1223\t0/0:87,0:87:0:0,0,1186\t0/0:78,0:78:0:0,0,870\t0/0:99,0:99:0:0,0,934\t0/0:95,0:95:0:0,0,1385\t0/0:82,0:82:0:0,0,1288\t0/0:96,0:96:0:0,0,1053\t0/0:60,0:60:0:0,0,1121\t0/0:112,0:112:0:0,0,1284\t0/0:69,0:69:0:0,0,715\t0/0:94,0:94:0:0,0,1454\t0/0:76,0:76:0:0,0,1180\t0/0:69,0:69:0:0,0,553\t0/0:81,0:81:0:0,0,1052\t0/0:99,0:99:0:0,0,1091\t0/0:62,0:62:0:0,0,430,variant_class:deletion,transcript_consequences:[{consequence_terms:[downstream_gene_variant],impact:MODIFIER,gene_id:ENSG00000227232,biotype:unprocessed_pseudogene,hgnc_id:38034,transcript_id:ENST00000423562,variant_allele:-,gene_symbol_source:HGNC,strand:-1,distance:4220,gene_symbol:WASH7P},{strand:-1,distance:4220,gene_symbol:WASH7P,canonical:1,gene_symbol_source:HGNC,variant_allele:-,transcript_id:ENST00000438504,hgnc_id:38034,impact:MODIFIER,consequence_terms:[downstream_gene_variant],gene_id:ENSG00000227232,biotype:unprocessed_pseudogene},{gene_symbol:DDX11L1,strand:1,distance:1867,gene_symbol_source:HGNC,transcript_id:ENST00000450305,variant_allele:-,hgnc_id:37102,biotype:transcribed_unprocessed_pseudogene,consequence_terms:[upstream_gene_variant],impact:MODIFIER,gene_id:ENSG00000223972},{gene_symbol_source:HGNC,canonical:1,gene_symbol:DDX11L1,distance:1726,strand:1,biotype:processed_transcript,gene_id:ENSG00000223972,consequence_terms:[upstream_gene_variant],impact:MODIFIER,transcript_id:ENST00000456328,variant_allele:-,hgnc_id:37102},{gene_symbol_source:HGNC,distance:4261,strand:-1,gene_symbol:WASH7P,gene_id:ENSG00000227232,consequence_terms:[downstream_gene_variant],impact:MODIFIER,biotype:unprocessed_pseudogene,transcript_id:ENST00000488147,variant_allele:-,hgnc_id:38034},{gene_symbol:DDX11L1,strand:1,distance:1729,gene_symbol_source:HGNC,transcript_id:ENST00000515242,variant_allele:-,hgnc_id:37102,biotype:transcribed_unprocessed_pseudogene,gene_id:ENSG00000223972,impact:MODIFIER,consequence_terms:[upstream_gene_variant]},{gene_symbol_source:HGNC,gene_symbol:DDX11L1,strand:1,distance:1731,biotype:transcribed_unprocessed_pseudogene,gene_id:ENSG00000223972,impact:MODIFIER,consequence_terms:[upstream_gene_variant],transcript_id:ENST00000518655,hgnc_id:37102,variant_allele:-},{gene_id:ENSG00000227232,impact:MODIFIER,consequence_terms:[downstream_gene_variant],biotype:unprocessed_pseudogene,variant_allele:-,hgnc_id:38034,transcript_id:ENST00000538476,gene_symbol_source:HGNC,strand:-1,distance:4268,gene_symbol:WASH7P},{variant_allele:-,transcript_id:ENST00000541675,hgnc_id:38034,consequence_terms:[downstream_gene_variant],impact:MODIFIER,gene_id:ENSG00000227232,biotype:unprocessed_pseudogene,strand:-1,distance:4220,gene_symbol:WASH7P,gene_symbol_source:HGNC}],assembly_name:GRCh37,seq_region_name:1,strand:1,start:10139,allele_string:AACCC/-,regulatory_feature_consequences:[{consequence_terms:[regulatory_region_variant],impact:MODIFIER,regulatory_feature_id:ENSR00000344265,biotype:TF_binding_site,variant_allele:-}],end:10143},ExAC.CHROM,ExAC.POS,ExAC.ID,ExAC.REF,ExAC.ALT,ExAC.QUAL,ExAC.FILTER,ExAC.AC,ExAC.AC_AFR,ExAC.AC_AMR,ExAC.AC_Adj,ExAC.AC_EAS,ExAC.AC_FIN,ExAC.AC_Het,ExAC.AC_Hom,ExAC.AC_NFE,ExAC.AC_OTH,ExAC.AC_SAS,ExAC.AF,ExAC.AN,ExAC.AN_AFR,ExAC.AN_AMR,ExAC.AN_Adj,ExAC.AN_EAS,ExAC.AN_FIN,ExAC.AN_NFE,ExAC.AN_OTH,ExAC.AN_SAS,ExAC.DP,ExAC.FS,ExAC.GQ_MEAN,ExAC.GQ_STDDEV,ExAC.Het_AFR,ExAC.Het_AMR,ExAC.Het_EAS,ExAC.Het_FIN,ExAC.Het_NFE,ExAC.Het_OTH,ExAC.Het_SAS,ExAC.Hom_AFR,ExAC.Hom_AMR,ExAC.Hom_EAS,ExAC.Hom_FIN,ExAC.Hom_NFE,ExAC.Hom_OTH,ExAC.Hom_SAS,ExAC.InbreedingCoeff,ExAC.VQSLOD,ExAC.culprit
Traceback (most recent call last):
File "/gpfs/software/genomics/phenopolis/DNASeq_pipeline/annotation/postprocess_VEP_json.py", line 6, in 
import exac
File "/gpfs/software/genomics/phenopolis/DNASeq_pipeline/annotation/exac.py", line 101, in 
c0=','.join([l[x].replace(',','/') for x in col0])
KeyError: '{id:.'

Could you please help me to resolve this issue.
Thanks In Advance
Fazulur Rehaman

**Comment by pontikos** [comment]
Hi, the input data is not the expected input.  In particular the field 'id' does not seem to exists in the dict c0.  Could you please put a print statement on the preceding line (line 100 of /gpfs/software/genomics/phenopolis/DNASeq_pipeline/annotation/exac.py) to see what c0 looks like?  Many Thanks, Nikolas.

**Comment by Fazulur** [comment]
Hi Nikolas,

Thanks a lot for your response.

Input data was generated using VEP v91 in json format. 
I am not able to use run_VEP.sh script since all databases were pointing to server.
Could you please suggest me how can I proceed with run_VEP.sh by piping postprocess_VEP_json.py.

postprocess command:

postprocess_VEP_json.py --file **vep-json/results/48samples.vep.json** --exac ref_data/Hsapiens/hs37d5/variation/exac.vcf.gz


exac.py script was failing at 100 line and not able to define c0. getting same error.
*** KeyError: '{id:.'

col0 variable has the below value

['{id:.', 'most_severe_consequence:upstream_gene_variant', 'input:1\\t10138\\t.\\tTAACCC\\tT\\t71.66\\tPASS\\tAC=1;AF=0.009434;AN=94;BaseQRankSum=-0.366;DP=4555;ExcessHet=41.744;FS=0;InbreedingCoeff=-0.3418;MLEAC=7;MLEAF=0.066;MQ=13.94;MQRankSum=1.98;NEGATIVE_TRAIN_SITE;QD=10.24;ReadPosRankSum=0.431;SOR=0.148;VQSLOD=-2.554;culprit=DP\\tGT:AD:DP:GQ:PL\\t0/0:122', '0:122:0:0', '0', '2394\\t0/0:71', '0:71:0:0', '0', '754\\t0/1:5', '2:7:53:53', '0', '114\\t0/0:89', '0:89:0:0', '0', '1164\\t0/0:108', '0:108:0:0', '0', '1394\\t0/0:95', '0:95:0:0', '0', '1455\\t0/0:86', '0:86:0:0', '0', '889\\t0/0:91', '0:91:0:0', '0', '1003\\t0/0:88', '0:88:0:0', '0', '1351\\t0/0:127', '0:127:0:0', '0', '1759\\t0/0:90', '0:90:0:0', '0', '1179\\t0/0:94', '0:94:0:0', '0', '1033\\t0/0:99', '0:99:0:0', '0', '1404\\t0/0:111', '0:111:0:0', '0', '1343\\t0/0:118', '0:118:0:0', '0', '1163\\t0/0:95', '0:95:0:0', '0', '1402\\t0/0:89', '0:89:0:0', '0', '1012\\t0/0:56', '0:56:0:0', '0', '813\\t0/0:55', '0:55:0:0', '0', '685\\t0/0:68', '0:68:0:0', '0', '440\\t0/0:67', '0:67:0:0', '0', '1044\\t0/0:44', '0:44:0:0', '0', '554\\t0/0:73', '0:73:0:0', '0', '803\\t0/0:70', '0:70:0:0', '0', '1077\\t0/0:89', '0:89:0:0', '0', '949\\t0/0:126', '0:126:0:0', '0', '1990\\t0/0:69', '0:69:0:0', '0', '755\\t./.:62', '0:62:.:0', '0', '0\\t0/0:59', '0:59:0:0', '0', '1023\\t0/0:67', '0:67:0:0', '0', '879\\t0/0:53', '0:53:0:0', '0', '573\\t0/0:106', '0:106:0:0', '0', '1295\\t0/0:95', '0:95:0:0', '0', '1223\\t0/0:87', '0:87:0:0', '0', '1186\\t0/0:78', '0:78:0:0', '0', '870\\t0/0:99', '0:99:0:0', '0', '934\\t0/0:95', '0:95:0:0', '0', '1385\\t0/0:82', '0:82:0:0', '0', '1288\\t0/0:96', '0:96:0:0', '0', '1053\\t0/0:60', '0:60:0:0', '0', '1121\\t0/0:112', '0:112:0:0', '0', '1284\\t0/0:69', '0:69:0:0', '0', '715\\t0/0:94', '0:94:0:0', '0', '1454\\t0/0:76', '0:76:0:0', '0', '1180\\t0/0:69', '0:69:0:0', '0', '553\\t0/0:81', '0:81:0:0', '0', '1052\\t0/0:99', '0:99:0:0', '0', '1091\\t0/0:62', '0:62:0:0', '0', '430', 'variant_class:deletion', 'transcript_consequences:[{consequence_terms:[downstream_gene_variant]', 'impact:MODIFIER', 'gene_id:ENSG00000227232', 'biotype:unprocessed_pseudogene', 'hgnc_id:38034', 'transcript_id:ENST00000423562', 'variant_allele:-', 'gene_symbol_source:HGNC', 'strand:-1', 'distance:4220', 'gene_symbol:WASH7P}', '{strand:-1', 'distance:4220', 'gene_symbol:WASH7P', 'canonical:1', 'gene_symbol_source:HGNC', 'variant_allele:-', 'transcript_id:ENST00000438504', 'hgnc_id:38034', 'impact:MODIFIER', 'consequence_terms:[downstream_gene_variant]', 'gene_id:ENSG00000227232', 'biotype:unprocessed_pseudogene}', '{gene_symbol:DDX11L1', 'strand:1', 'distance:1867', 'gene_symbol_source:HGNC', 'transcript_id:ENST00000450305', 'variant_allele:-', 'hgnc_id:37102', 'biotype:transcribed_unprocessed_pseudogene', 'consequence_terms:[upstream_gene_variant]', 'impact:MODIFIER', 'gene_id:ENSG00000223972}', '{gene_symbol_source:HGNC', 'canonical:1', 'gene_symbol:DDX11L1', 'distance:1726', 'strand:1', 'biotype:processed_transcript', 'gene_id:ENSG00000223972', 'consequence_terms:[upstream_gene_variant]', 'impact:MODIFIER', 'transcript_id:ENST00000456328', 'variant_allele:-', 'hgnc_id:37102}', '{gene_symbol_source:HGNC', 'distance:4261', 'strand:-1', 'gene_symbol:WASH7P', 'gene_id:ENSG00000227232', 'consequence_terms:[downstream_gene_variant]', 'impact:MODIFIER', 'biotype:unprocessed_pseudogene', 'transcript_id:ENST00000488147', 'variant_allele:-', 'hgnc_id:38034}', '{gene_symbol:DDX11L1', 'strand:1', 'distance:1729', 'gene_symbol_source:HGNC', 'transcript_id:ENST00000515242', 'variant_allele:-', 'hgnc_id:37102', 'biotype:transcribed_unprocessed_pseudogene', 'gene_id:ENSG00000223972', 'impact:MODIFIER', 'consequence_terms:[upstream_gene_variant]}', '{gene_symbol_source:HGNC', 'gene_symbol:DDX11L1', 'strand:1', 'distance:1731', 'biotype:transcribed_unprocessed_pseudogene', 'gene_id:ENSG00000223972', 'impact:MODIFIER', 'consequence_terms:[upstream_gene_variant]', 'transcript_id:ENST00000518655', 'hgnc_id:37102', 'variant_allele:-}', '{gene_id:ENSG00000227232', 'impact:MODIFIER', 'consequence_terms:[downstream_gene_variant]', 'biotype:unprocessed_pseudogene', 'variant_allele:-', 'hgnc_id:38034', 'transcript_id:ENST00000538476', 'gene_symbol_source:HGNC', 'strand:-1', 'distance:4268', 'gene_symbol:WASH7P}', '{variant_allele:-', 'transcript_id:ENST00000541675', 'hgnc_id:38034', 'consequence_terms:[downstream_gene_variant]', 'impact:MODIFIER', 'gene_id:ENSG00000227232', 'biotype:unprocessed_pseudogene', 'strand:-1', 'distance:4220', 'gene_symbol:WASH7P', 'gene_symbol_source:HGNC}]', 'assembly_name:GRCh37', 'seq_region_name:1', 'strand:1', 'start:10139', 'allele_string:AACCC/-', 'regulatory_feature_consequences:[{consequence_terms:[regulatory_region_variant]', 'impact:MODIFIER', 'regulatory_feature_id:ENSR00000344265', 'biotype:TF_binding_site', 'variant_allele:-}]', 'end:10143}']

could you please suggest me how can I proceed further?

Thanks & Regards
Fazulur Rehaman

**Comment by Fazulur** [comment]
Hi Nikolas,

Could you please give me suggestions on using run_VEP.sh and postprocess_VEP_json.py using our server. 

Thanks In Advance
Fazulur Rehaman
