### ISSUE TITLE
 /phenogenon_json/HP:0001098 error

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenopolis#66]
```
Exception on /phenogenon_json/HP:0001098 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rmhanpo/phenopolis/views/__init__.py", line 181, in decorated
    return f(*args, **kwargs)
  File "/home/rmhanpo/phenopolis/views/hpo.py", line 68, in phenogenon_json
    phenogenon(hpo_id, lit_genes, omim_genes, recessive_genes, dominant_genes)
  File "/home/rmhanpo/phenopolis/views/hpo.py", line 24, in phenogenon
    print(len(temp))
TypeError: object of type 'NoneType' has no len()
```

**Comment by pontikos** [comment]
the temp variable can be None so failed, i have fixed this.
